### ISSUE TITLE
Settings: Settings are not saved properly anymore

### ISSUE THREAD

**Issue by harrwiss** [wokhansoft/WFN#104]
Exception thrown: 'System.Configuration.ConfigurationErrorsException' in System.Configuration.ConfigurationManager.dll
DEBUG [  1] - Setting is not part of the current section. Skipping. [OverwriteSetting() in CustomSettingsProvider.cs, line 212]

Problem is with application settings:
AlwaysRunAs
UseBlockRulesGlobal
EnableServiceDetectionGlobal

**Comment by wokhan** [comment]
Hi, those ones are handled differently if I remember correctly (cannot check yet).... I had to quickly fix regressions with configuration handling (which was in fact not working at all anymore),  sorry those three ones passed through.

**Comment by harrwiss** [comment]
Did some more investigations:

The seetings mentioned above are in the "applicationSettings" section.

However, I found that even before on line 146 in *CustomeSettingsProvider* the following exception is thrown **silently** during save:

`Exception thrown: 'System.Configuration.ConfigurationErrorsException' in System.Configuration.ConfigurationManager.dll
It is an error to use a section registered as allowExeDefinition='MachineToRoamingUser' beyond the roaming user config, in the local user config.`

* the mentioned *MachineToRoamingUser* setting is in in *app.config* "userSettings" 
 * btw: do you know why this exception does not catch in a try/catch block (tried to add one)? Only when I select it in the Exception Settings > Break when thrown I get the exception above.
  * ... without selecting the *Exception Settings* to *break when thrown*, only this line is shown in the debug output, but it's not catched: 
`Exception thrown: 'System.Configuration.ConfigurationErrorsException' in System.Configuration.ConfigurationManager.dll`

In addition I noted, that in *user.config* (local and roaming) the userSettings section exists twice (1 section for old and new namespace). Therefore it's probably necessary to delete or migrate the user.config files first (should be done automatically in code).

Unfortunately I'm not sure at the moment, how it was intended to work.

Questions:
* Why do we even try to save applicationSettings in user.config (local/roaming) since they, to my understanding, should not be changeable by a user?

**Comment by harrwiss** [comment]
Hi @wokhan, after further investigation I think we could also do without CustomSettingsProvider today (incl. all its complexity) and just use the default LocalFileSettingProvider.

Advantages:
- much simpler code without having to deal with individual settings 
- works better together with vs tools
- .net takes care about what should be stored in which config file (roaming, user, ..)
- versioning of user config files
- reset, previousVersion, migrate functions are implemented as well (IApplicationSettingsProvider)

Disadvantages:
- it uses it's preset ExeConfigurationFileMap i.e. we have less control on path/file-naming for user.config files

What do you think?

**Comment by harrwiss** [comment]
Hi @wokhan, because saving settings was not working I went ahead and implemented LocalFileSettingProvider which provides standard behaviour. Now CustomSettingsProvider extends from LocalFileSettingProvider.

Form me it seems to work well together with the SettingsDesigner.

**Comment by harrwiss** [comment]
@wokhan: If there is a need to use another location we could use the approach described here: 
https://stackoverflow.com/a/45550582

**Comment by wokhan** [comment]
Hi @harrwiss, at the old times I implemented a custom settings provider because by default the config system relies on current app name (as you saw).
Meaning that Notifier.exe (and other processes) couldn't use WFN.exe.config (or WFN.dll.config).
I'd be surprised if it was working now... does it ? :)

**Comment by harrwiss** [comment]
From what I've seen it works with Notifier as well, but I noticed, that the setting's Notifier modifies (in the background) are stored in separate sub-dir below *AppData\Local\Wokhan_Solutions* folder based on strict isolation rules: ```<App Name>_<Evidence Type>_<Evidence Hash>\<Version>\user.config```

I think, this is per-se not a problem and has also some advantages, but we could also implement *HostSecurityManager* as described in the link above when needed (haven't made up my mind yet) 😏 .

**Comment by wokhan** [comment]
I'm really really really surprised Notifier manage to get its settings from WFN.dll.config ^^ OpenExeConfiguration clearly takes currently running assembly's config file, so....
But if you tested and it works, I guess I'll have to take it as granted. I'll test it though, but for my own culture ;-)

**Comment by wokhan** [comment]
Hi @harrwiss, I checked what configuration file Notifier was using, and it's definitely not WFN.dll.config since it's not overridden.
Hence any Notifier-related option is ignored.
Are you 100% sure it was working on your side?
Thanks

**Comment by harrwiss** [comment]
Hi @wokhan, sorry for the late answer - I'm looking into it's excact behaviour, but how MS implemented Settings is a pain and much too complicated for my taste, but there must have been reasons it 🤔 

Here is what I found so far:

### During development when editing with Settings.Designer UI:
1. Settings.settings contains the definition incl. scope (user, roaming) and default values
   * Note: To see all configuration options you need to open the file with a text editor e.g. scope is not shown on the ui
1. Settings.Designer.cs is auto-generated and contains all setters/getters incl. defaults
1. app.config is auto-generated as well
1. app.config becomes WFN.dll.config when building (its renamed in post event) 

### The configurations are read in the following order during startup:
1. WFN.dll.config and/or Settings.Designer.cs (execonfig)
1. user.config (roaming)
1. user.config (local)

### WFN.dll.config is in fact read-only, because: 
* when the user changes a setting, *user.config* is updated in *c:\Users\[User]\AppData\Wokhan_solutions*
* makes sense, because a user may not have rights to update it e.g. when installed in *Program Files*
* the \<applicationSettings\> section is by design always readonly - thats why *Settings.Designer.cs* has no setters for these settings

Do you agree so far or did I miss something ❓

**Comment by wokhan** [comment]
Hi @harrwiss, 

You are right, configuration through .Net Configuration Manager is a real pain to get customized (and doesn't really fit .Net Core modular philosophy).

Your description is alright ; regarding the WFN.dll.config file rename, as you saw it takes current assembly's name (so... Wokhan.WindowsFirewallNotifier.Common.dll.config) which it, well.... not what we want, hence the rename.
Not sure about the settings load order though (between roaming and local), but it's described properly on MS docs regarding configuration so should be easy to check :-)

Now since renaming it from WFN.config to WFN.dll.config breaks previous users configuration anyway, maybe **we should simply throw away this configuration handling and move to a modern json based configuration (as defined and standardized for .Net Core)**.

Should simplify things (and be more interesting also ;-) )

**Comment by harrwiss** [comment]
Hi @wokhan, I've spend hours trying to figure out how to make the LocalFileSettingsProvider do what we need. The solution described in https://stackoverflow.com/a/45550582 would have been exaclty what's needed, but doesn't work with netCore31 ☹️. Do you have any idea how to do that?

Basically, the only problem we have is: Sharing the same user settings between WFN and Notifier i.e. when changing for instance the AccentColor in WFN options, they must also be reflected in Notifier.

Reverted back and tried to fix the CustomSettingsProvider but also here no luck - giving up now. 

What I've seen so far (tested with Notifier primarely):
- there are exceptions during startup caused by LogHelper when accessing settings - these can be fixed though
- some settings are written to the Roaming user.config (e.g. AlwaysShowDetails) but also exist in local user.config and have therefore no effect (anymore)
- In Settings.cs *[SettingsProvider(typeof(CustomSettingsProvider))]* doesn't work (as you noted) but it works perfectly when extending CustomSettingsProvider from LocalFileSystemProvider instead of SettingsProvider. I also have no clue why 🤕 
- The workaround implemented in Settings.cs does not call *SettingsPropertyValueCollection* in CustomSettingsProvider

>We should simply throw away this configuration handling and move to a modern json based configuration (as defined and standardized for .Net Core

Well I'm absolutely happy with anything that works (preferably also with the Settings designer). However, **just simply switching from xml to json would not change much**. 

I'm giving this back to you now.

**Comment by harrwiss** [comment]
Hi @wokhan, I reverted the changes for *LocalFileSettingsProvider* and pushed the fixes I did so far to this stream for your reference.

**Comment by wokhan** [comment]
> Well I'm absolutely happy with anything that works (preferably also with the Settings designer). However, **just simply switching from xml to json would not change much**.

Hi @harrwiss, it's not about a simple switch, it's about using the embedded configuration management logic that comes with .Net Core (and which is using json files). Settings designer and app.config files were the WPF era way of doing this, I didn't change for .Net Core's way since I didn't want to break anything for existing users, but after second thought and since we have some issues making it work as expected, it should be worth trying.

Thanks for the revert and sorry you had to do this! I should be able to merge now.
