### ISSUE TITLE
Temporary Rule stays onscreen until it is dismissed

### ISSUE THREAD

**Issue by n00b42** [wokhansoft/WFN#11]
Temporary Rule stays onscreen until it is dismissed using the Tray-Icon,
because of that other firewall notifications do not pop up.

Example: Some Setup:
setup.exe - wants to access network => temporary rule
loads another setup (e.g. some framework) - wants to access network => no notification as other notification still on top

**Comment by non-hp01** [comment]
Having the same issue with Windows 10 Creators Update (1703)

**Comment by AtlasHackert** [comment]
This issue has been fixed in the just released v2.0 Beta 3!
