### ISSUE TITLE
[bug v2019.12-u5-beta] Pop-up advanced options layout needs to scroll to show all options

### ISSUE THREAD

**Issue by danielmmmm** [wokhansoft/WFN#110]
WFN was driving me crazy for some weeks (months?) now with constant pop-ups for applications I already allowed or blocked. Now I found the cause of my troubles: The pop-up shows the advanced options in only one column, which is scrollable. Everything below the "Remote port" switch is hidden, until I scroll down ... which I did not do until now :-)

This is what my pop-up looks like:
![Clip1](https://user-images.githubusercontent.com/3389179/80807733-3bb53580-8bbe-11ea-9f67-8c7ab0fc37d1.png)

This is what it is supposed to look like:
![Clip1](https://user-images.githubusercontent.com/23364684/28368473-1b5fcc98-6c9d-11e7-830d-a1fe299a7348.PNG)

**Comment by wokhan** [comment]
Hi, thanks for your feedback.
This modification was made a few versions ago, and a new option is coming to chose the layout (defaulting to the column view you are mentioning).
Closing this as it's already in the nightlies (so it will make it in WFN 2.1).

**Comment by danielmmmm** [comment]
Great! Thanks for the info.
Do you, by any chance, publish nightlies (binaries) somewhere? I hope I didn't open Pandora's box with this question :-D

**Comment by wokhan** [comment]
Hi @danielmmmm, sorry I didn't answer before: nightlies are automatically published in the Releases page. As of now I think you should wait for a nightly build with a fix for issue #111 ...

**Comment by danielmmmm** [comment]
Thanks, I am playing with 2.1.138.0 now :-)
