### ISSUE TITLE
Settings management rewrite

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#111]
Due to issues mentioned in https://github.com/wokhansoft/WFN/issues/104#issuecomment-616145242, the settings implementation must be rewritten and simplified.

Goals:
- allow default application and user level values.
- allow user level settings override in user's local folder (by default - of course the settings file in the app folder can still be overwritten manually, ensuring portable mode actually stays portable for those who want it to; might add an option about this).
- KISS

Note: investigating .Net Core settings management (using Microsoft.Configuration.Extensions), while still allowing the use of the settings designer.

**Comment by wokhan** [comment]
90% done, keeping the designer (@harrwiss that's for you ;) ) while using the new settings management from .Net Core (a bit customized though).

**Comment by wokhan** [comment]
I finally had a better idea this morning and rewrote a veryyyy simplified implementation, still based on .Net Core 3.1 configuration management (a bit), while keeping the designer as well.
Working properly now and will allow a real portable mode for settings as well (not implemented yet, but easy to do).

**Comment by harrwiss** [comment]
So far looks pretty good :)
