### ISSUE TITLE
Start with another menu item

### ISSUE THREAD

**Issue by hoasis2** [wokhansoft/WFN#112]
On avarage it takes approx. 6 seconds WFN shows all the active connections on start-up. Until then you cannot select anything else from the menu and therefore have to wait.

Wouldn't it be better, if WFN started with another submenu, for example w/ "firewall settings"? :)

**Comment by wokhan** [comment]
Hi @hoasis2, indeed the current version was too slow when opening up.
The next version solves the issue, the UI responds immediately after launch. It's not ready for a public release though (while available in the nightlies... but some issues with the settings need to be fixed first, see issue #111 for more information).

**Comment by hoasis2** [comment]
I'll try the nightlies, thx.
