### ISSUE TITLE
Survey (sort of)! Merge Connections / Bandwidth / Map pages

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#114]
While using the latest alpha, I wondered why I initially split the connections listing, bandwidth monitoring and real time map pages, while all info pertain to the same connections.
I wonder if it would not be smarter to merge the three in a Monitoring page, showing the bandwidth directly on the same screen (with a kind of mini graphs for each process?), and allowing the map to be shown / hidden on demand right below it.
Your thoughts, everybody?

**Comment by hoasis2** [comment]
Please change the frontpage of the application from "`connections`" to "`firewall settings`".

That aside, merging "connections", "bandwidth" and "map" that way you describe is a very good idea if that page respondes fast.

I'm not using the map at all. :)

**Comment by wokhan** [comment]
Thank you @hoasis2, I'll add an option to pick the default page. And be sure it will be fast (alpha was already faster, and there was other improvements since).

**Comment by theorist-complex** [comment]
I think what you describe sounds good, but really, Im not too picky. This is my favorite software of this type and mostly just want to give you some encouragement.
