### ISSUE TITLE
I want binary.

### ISSUE THREAD

**Issue by mtwwstj9** [wokhansoft/WFN#12]
Hi,I'm using WFN and thanks for develop.
Today I want to update WFN and see codeplex.
There is "move to github".(also codeplex shutdown)
In github-WFN I can't find out binary.
Perhaps compiling from source require Visual Studio.
It is high wall for me. (only user)
I heard this feature https://help.github.com/articles/about-releases/
It sounds good.isn't it?

**Comment by AtlasHackert** [comment]
If you click on the "releases" 'tab' on the main WFN github page, it'll take you [here](https://github.com/wokhansoft/WFN/releases).

**Comment by mtwwstj9** [comment]
Ouch! I've mistaken.I'm sorry,and get new proposal,too.
"No description or website provided." on top page.
 To "If you want binary,click 'releases' next to 'commits' and 'branch'.".
I think a lot of average user(like me) would return,but this is only draft.

**Comment by wokhan** [comment]
Done, sorry for the delay :)
