### ISSUE TITLE
Possible to create a portable version?

### ISSUE THREAD

**Issue by Gitoffthelawn** [wokhansoft/WFN#15]
Would it be possible to create a portable version?

Windows Firewall Control by Sphinx Software (http://sphinx-soft.com/Vista/order.html) is able to offer a portable version.  It would be great if this open-source project could do the same.

**Comment by AtlasHackert** [comment]
Can you explain to me in what wat WFN can be made more portable?

**Comment by Gitoffthelawn** [comment]
Yes.  No installer or MSI file.  A simple executable (with any support libraries) that can be copied into a single directory and run from there.

**Comment by AtlasHackert** [comment]
That's exactly what WFN has currently?

**Comment by Gitoffthelawn** [comment]
I thought I read something about only offering it as an MSI file.  I might have been mistaken.  Was I?

**Comment by AtlasHackert** [comment]
There are plans of making a MSI installer version in the (distant?) future, but currently, WFN is only distributed as a zip-file without installer.

**Comment by Gitoffthelawn** [comment]
Thanks.  If an MSI installer version is created, will the non-installer version still be made available?

**Comment by AtlasHackert** [comment]
Yes.

**Comment by Gitoffthelawn** [comment]
Great!  Thank you!
