### ISSUE TITLE
Installer and Portable mode

### ISSUE THREAD

**Issue by tgp1994** [wokhansoft/WFN#21]
This issue is to discuss the need for an installer for releases, and the addition of a "portable mode" to complement this.

## Installer
@AtlasHackert:
>Preferably an .msi, so that WFN can be pushed onto machines in a domain. However, I have no experience with this, and it seems quite complicated; that's why I haven't tried it yet.

Domain/IT friendliness sounds like a goal here. Visual Studio 2017 currently has [an extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2017InstallerProjects) for creating installer projects, which I think is what we're looking for. [Here](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components) is apparently a modern article from Microsoft on deploying applications. Our options appear to be:

1. Publish a Windows app
2. Deploy with ClickOnce (may be useful for domains/orgs)
3. Create an MSI-based WiX installer (probably what we're looking for)

## Portable mode
While on the subject of installing, users may desire to continue using WFN as it currently operates; in a self-contained, portable mode. It should keep (most) of its file operations restricted to its own running directory at the time. In normal (non-portable) mode, WFN is installed to the Program Files directory, and under Windows rules no further writing will occur within that directory. Since WFN supports Vista or higher, it may be worthwhile to reference [this Microsoft Developer blog post](https://blogs.msdn.microsoft.com/cjacks/2008/02/05/where-should-i-write-program-data-instead-of-program-files/) for guidance on which files should go where.

**Comment by RoyiAvital** [comment]
Any chance for a @PortableApps flavored portable mode?

**Comment by wokhan** [comment]
Sorry for the delay, I'm not able to work on this project as much as I'd like to (well, I didn't for years and the project continued thanks to @AtlasHackert)... I hope I'll get back on it soon to help fixing / improving v2.
Regarding your statement, in fact I hate installers and MSIs, this is why there is none... Enterprise deployment could be managed by a custom script (but anyway it's a tool for power users and it shouldn't be used in enterprises).

Regarding a portable apps flavor, it should be easy to provide but one has to keep in mind that the outgoing notification should be kept disabled then (it's the only part in WFN that requires it not to be moved once enabled).
And finally, regarding a Windows Store version, I'll do one ultimately (keeping it open source of course). I'm used to it so it would be easy... Stay tuned!

**Comment by RoyiAvital** [comment]
@wokhan ,
Currently, does the program writes anything to registry or outside its working directory?
Is there a way to make it work without Administrator Privileges (Even if it means reduced capabilities)?

**Comment by AtlasHackert** [comment]
WFN currently saves the settings in the appropriate AppData-folders, under the user account. WFN needs Administrator-rights to register (and unregister) the popup, and you need Administrator-rights to add/remove firewall rules. I don't think it's going to get much more portable than it already is?

**Comment by RoyiAvital** [comment]
@AtlasHackert ,
I would be happy if I could have option to have "View Only Mode" with no Administrator Privileges.

Regarding data, it would be great if there was an option to make it save the settings file in the working directory of the application.

**Comment by wokhan** [comment]
Should be easy to keep the settings file locally, but as @AtlasHackert mentioned, WFN is already "portable" as long as you don't enable the notifications. We can add an option anyway...

**Comment by RoyiAvital** [comment]
@wokhan ,
It would be great!

Also, what about a mode which doesn't require Administrator Privileges?
I know it will limit features.
Could we have "View Only" mode without Administrator Privileges?

**Comment by wokhan** [comment]
You should already be able to launch it as a standard user, with limited access to security features... But I have to admit I haven't tried for a long time, I'll check that asap. 
@AtlasHackert : Not the right place to say hi, but hi! ;-)

**Comment by geotavros** [comment]
Not sure if this was fixed already but earlier I had a crash window appear every time firewall blocked the connection. This happened when being logged in as Guest on a PC with WFN enabled.

**Comment by RoyiAvital** [comment]
@wokhan ,
When I double click it it asks for Administrator Privileges (UAC).
If I click **No** it won't run (Nothing happens).

Is there a different way to run it as regular user?

**Comment by AtlasHackert** [comment]
@geotavros: Windows 7 or 8, I presume? (I believe the Guest-account is unsupported by Microsoft in Windows 10.)
@wokhan: Hi to you too! :D

**Comment by RoyiAvital** [comment]
Any update on working in non administrator mode?

**Comment by DJCrashdummy** [comment]
perhaps my comment at https://github.com/wokhansoft/WFN/issues/53#issuecomment-476369847 may be interesting for this discussion too. ...and hopefully you know [Chocolatey](https://chocolatey.org/).

**Comment by RoyiAvital** [comment]
I'm more worried about being able to make it work without Admin rights.

**Comment by DJCrashdummy** [comment]
AFAIK (i'm using windows very occasionally) installing/updating via chocolatey has nothing to do with working with or without admin rights.

**Comment by RoyiAvital** [comment]
@DJCrashdummy , I was talking about running the program itself.

I actually like better Windows approach of installers instead of Linux Style of Chocolatey.

**Comment by wokhan** [comment]
Almost a year later: we may have a look at how we can separate admin features from non admin ones, but I'm afraid functionality will be quite limited without admin rights (no process information, no device stats, and so on...). If the console is unusable, it would be useless to allow a non-admin version 🙄

**Comment by wokhan** [comment]
Closing the issue as the installer will be added to the roadmap.
Regarding my previous post, comment will be updated later to confirm it cannot be done, once verified.
