### ISSUE TITLE
WFN hangs on large logs

### ISSUE THREAD

**Issue by boldcompany** [wokhansoft/WFN#22]
Thanks for developing this really cool piece of software. You've engineered a much-needed tool that sits at the intersection of (a) security events on Windows Server, (b) network monitoring, and (c) local and easy to use.

Trying out latest WFN on a Windows Server 2012 machine.

When trying to look at the security log (which has about 50,000 entries), WFN hangs indefinitely and never completes the view. I can look at the same log in Event Viewer and other utilities with no problem, so it's not a machine issue. What am I doing wrong, or can you improve on the log parsing performance?

**Comment by boldcompany** [comment]
Any thoughts?

**Comment by boldcompany** [comment]
Anyone here?

**Comment by TekieG** [comment]
the logs that WFN creates? inside of the WFN folder?

**Comment by AtlasHackert** [comment]
Can you check if this issue is still present in the just released v2.0 Beta 3? I've made some improvements to the security log loading.

**Comment by harrwiss** [comment]
As far as I can remember, I fixed an issue where it showed more than the 1500 entries in the counter sometimes, because it didn't correctly remember the last seen entry. Havent' seen this behaviour for some time now.

**Comment by wokhan** [comment]
@harrwiss / @AtlasHackert, I'm not yet merging to master since I think there is some weird random issue / conflict between real time events and currently enumerated ones.
Consequently, more testing would be great... Could you please try to checkout the bugfix/securitylog_perf branch and tell me how it goes for you?
Thanks!!!!!

**Comment by harrwiss** [comment]
Ok, will check it out now

**Comment by wokhan** [comment]
Thanks! Oh and I just figure out the "auto refresh" button shouldn't be handled the way I did with the new event listener.
When disabled it should still listen but push events to a temp list, to be able to inject them when reenabling it.
Cannot do that now, if I take my laptop in the car, I'll really really appear as a non-involved geeky father/husband 😁

**Comment by harrwiss** [comment]
Hi @wokhan, there is definitively some problem there.

The behaviour is:
1. Choose Security log
2. It starts loading the events in the progress counter
3. Than it freezes when the counter reaches ~6000 and the console becomes totaly unresponsive and doesn't recover

![image](https://user-images.githubusercontent.com/33778373/76159880-15769a80-6125-11ea-9d87-0d06496e4737.png)

When I pause the debugger its in here:
![image](https://user-images.githubusercontent.com/33778373/76159949-fdebe180-6125-11ea-9308-b978816393cc.png)

BTW: I would limit the number of entries anyway to a reasonable amount (2-3000K max). Also consider, that the DNS resolver may dutyfully try to resolve all the ips to hostnames in the background.

**Comment by wokhan** [comment]
You're totally right, I made a noob mistake. Since I have a few matching events, it wasn't an issue for me. 
I'll add back the limitation since this is something I can do l  my phone 😁

**Comment by harrwiss** [comment]
You think the phone is less obvious to your wife and children then ... 😄 

Did some further investigation:
* removing the lock on that line resolves the deadlock situation - it seems to be in conflict with the lock in the method *SecurityLog_EntryWritten*
![image](https://user-images.githubusercontent.com/33778373/76160521-1d393d80-612b-11ea-983a-2e827e34d1c2.png)
.. after that it seems to work fine

Other observations:
* Auto-refresh not working (think you mentioned that above)
* Try also to turn on this in the options to get more events being triggered:
![image](https://user-images.githubusercontent.com/33778373/76160572-989aef00-612b-11ea-85a6-cda9e6abaec9.png)
* going to another page and back re-loads the whole event log every time

If it's ok I'll push the quick fix to your branch and maybe I find something else.

Cheers and enjoy the sunny day (at least here in Switzerland it's very nice today.

**Comment by wokhan** [comment]
Thank you and ok you can update the branch (if not already, I cannot check as often since I'm not in the car anymore 😁😉).
I'm surprised there isn't any side effects with the lock removal, but we'll, if it works... 
Enjoy the sun as well!

**Comment by wokhan** [comment]
Weirdly, removing the second lock seems to have no impact as well (so... useless?! but I'd swear it fixed an issue on my side at a given time).

And I think I can easily remove the limit anyway, by resolving DNS and loading icons when needed only (easy to do). That way it should prove easy on memory and even CPU (computing only displayed data), while removing the need to go to the actual Event log viewer (which is in fact slower, at least on my computer) if in need for more events.

Keeping the branch apart til this is implemented.

**Comment by wokhan** [comment]
Update : I know there is something wrong in the code I rewrote for the dns resolver, cannot fix this morning. Will do that later.

**Comment by wokhan** [comment]
Additional tests required as it looks like some icons are missing, and DNS resolution also seems to raise a lot of errors.

I merged the branch anyway but issue's still to be checked.
