### ISSUE TITLE
Crash with "Outbound" set to "Block and prompt" on Windows Server 2008/2016

### ISSUE THREAD

**Issue by danielmmmm** [wokhansoft/WFN#23]
I'd like to block outgoing traffic and only allow few components/programs. Whenever I activate "Block and prompt" for outgoing traffic, WFN crashes repeatedly.

Here are event logs for .NET Runtime:
```
Application: Notifier.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at Wokhan.WindowsFirewallNotifier.Common.Helpers.LogHelper..cctor()

Exception Info: System.TypeInitializationException
   at Wokhan.WindowsFirewallNotifier.Common.Helpers.LogHelper.Debug(System.String)
   at Wokhan.WindowsFirewallNotifier.Notifier.Program.Main(System.String[])
```

and the accompanying Application Error:
```
Faulting application name: Notifier.exe, version: 2.0.0.0, time stamp: 0x59317d16
Faulting module name: KERNELBASE.dll, version: 10.0.14393.1770, time stamp: 0x59bf2bcf
Exception code: 0xe0434352
Fault offset: 0x000daa12
Faulting process id: 0xd5c
Faulting application start time: 0x01d34f0adc2aa405
Faulting application path: C:\Portable Program Files\WFN\Notifier.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 7eff7d23-4fa5-4142-a7bf-15a1e2f21b84
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by TekieG** [comment]
Move it to documents folder and see if it works. that's the only way I was able to make it work. I can't exactly remember why I just read about it. I'll look it up, in the mean time try moving it to the documents folder.

**Comment by danielmmmm** [comment]
Thanks for your suggestions. Yes, WFN is running as administrator on my system.

It looks like moving WFN to the documents folder did the trick. I will continue testing :-)

**Comment by TekieG** [comment]
the outgoing connections are blocked to begin with and only allowed if user presses the "allow" after that. it is always allowed. Unless the same connection has a different parameter. For example, you can allow adobe.exe to connect to IP address that is in UK per say. but itll be blocked by WFN if it connects to IP address in the US, at least until you allow it.

**Comment by wokhan** [comment]
Closing the issue as it is fixed or will be soon following Notifier launching logic rewrite.
