### ISSUE TITLE
What happens if I close WFN, will it keep blocking?

### ISSUE THREAD

**Issue by fabionar** [wokhansoft/WFN#25]
I find it very strange compared to tinywall, where the blocking by .exe is pretty simple by simply finding the path and setting to block. WFN instead must wait for a request, and consumes more RAM.

**Comment by AtlasHackert** [comment]
WFN is built specifically to provide a notification if the Windows Firewall blocks a connection. It's not meant as a complete interface to it. You can use the Windows Firewall control panel for that.

Additionally, WFN consumes zero RAM if you close the console, as there are no components that need to remain loaded for WFN to work.
