### ISSUE TITLE
Connections from WSL are not detected

### ISSUE THREAD

**Issue by vktec** [wokhansoft/WFN#26]
When connecting to an SSH session from the Windows Subsystem for Linux, I get the error `ssh: connect to host aaa.bbb.ccc.ddd port xx: Permission denied` with no notification to let me know there has been a request and no entry in the security log.

This may be a result of how WSL is implemented, since it's part of the kernel, but you'd think if it can be blocked by the Windows Firewall it'd show up as something.

**Comment by AtlasHackert** [comment]
True, this is a limitation of the current implementation of the Windows Firewall and WSL. See: https://github.com/wokhansoft/WFN/issues/3

**Comment by vktec** [comment]
Oops. I missed that other issue. Thanks!
