### ISSUE TITLE
Can't allow outgoing traffic for Ubuntu bash on Windows

### ISSUE THREAD

**Issue by DomenicoCasillo** [wokhansoft/WFN#3]
With the current version (2.0 Beta 1) and the previous alpha, i'm not able to allow outgoing traffic for the ubuntu bash. When i run apt-get upgrade for example WFN popup reports a "Pico" application (see screen below). Even if i allow all kind of traffic it keeps asking me to allow such application and the outgoing traffic is never allowed.

[https://drive.google.com/open?id=0B1ToRp4AD1hkSW8tSEdKWDdxV0k](url)

**Comment by AtlasHackert** [comment]
This is a bug/limitation in Windows: see https://github.com/Microsoft/BashOnWindows/issues/722
So there's currently nothing we can do about that. :(

**Comment by wokhan** [comment]
https://github.com/microsoft/WSL/issues/722#issuecomment-394874189

Closing since WSL team fixed this (and WSL2 is here so... Might not be still an issue).
