### ISSUE TITLE
DNS Server Role (dns.exe) and Combining Rules - Windows Server 2016

### ISSUE THREAD

**Issue by SyrianBallaS** [wokhansoft/WFN#31]
This is a great program and helps me secure my network by addressing some shortcomings of Windows Firewall (not logging/notifying outbound connections) but there are some issues.

**Summary**
1. It seems because the DNS role has around 6330 connections, it causes the GUI to hang.
2. Combining rules makes WFN think WF blocked an outbound connection, like instead of having separate rules for allowing HTTP/HTTPS for a program, you'd put them in one. When they are separate WFN doesn't say anything (expected) but if they are not separate; WFN will say WF blocked it when it was not blocked.

**Possible Resolution**
- For the first one, I think it shouldn't even be included since it's not applicable since it doesn't really make sense for a server to block its own DNS
- I'm not really sure about the second one

**Comment by AtlasHackert** [comment]
About #1: Known issue; if a misbehaving program retries too fast/too often, that will put serious stress on WFN. Not much we can do about that, except complain to that program's author.
About #2: if WFN claims the connection got blocked, then it certainly wasn't allowed through the Windows Firewall, so your combined rule appears to be broken.

**Comment by wokhan** [comment]
First issue will be fixed (or is already).
Second one.... as stated by @AtlasHackert , if it appears blocked, then it means Windows Firewall actually logged a blocked connection as well, nothing we can do about it :-/
Closing...
