### ISSUE TITLE
im sorry to ask this but how to uninstall...

### ISSUE THREAD

**Issue by helppe** [wokhansoft/WFN#33]
hello,

ok im not trolling... i tryed the program yesterday, and i have many many notifications to allow without knowing what are they: for example: bonjour, system etc... and even if i allow them they come back later with an other notification. so maybe my actions are not validated.

anyway, how can i uninstall it since there is no installation process, so i wonder how to do?
should i just clic "disable" in the firewall settings? 

thx

**Comment by AtlasHackert** [comment]
In the same screen (WFN, Firewall Settings), put "Outbound" back to "Allow".

**Comment by helppe** [comment]
thanks

**Comment by AtlasHackert** [comment]
Glad I could help.
