### ISSUE TITLE
[feature request] option to start (minimized) with OS boot

### ISSUE THREAD

**Issue by ghost** [wokhansoft/WFN#35]
It would be good if there was an option that WFN would start/autorun (minimized to the tray) upon OS boot (login)

**Comment by AtlasHackert** [comment]
That makes sense; I'll put it on the ToDo list!

**Comment by harrwiss** [comment]
The new version starts the Notifier automatically after login and it can be minimized to the tray already. 

Todo:
* Add a configuration setting for the user (start after login and minimize on startup)
* As far as I now a command-line option "-minimize" was already added to the tasktemplate.xml but is not used in Notifier yet

**Comment by wokhan** [comment]
Could be why the task failed launching on my branch, if it's only minimize, the command line parser (a dumb one I quickly wrote) expects a value after the parameter name (-minimize 1 for instance).

You can move the card in "in progress" in the project page then 👍
