### ISSUE TITLE
In security log, do not redraw window contents unnecessarily

### ISSUE THREAD

**Issue by kekukui** [wokhansoft/WFN#38]
WFN is constantly re-drawing the security log window contents when no new activity has occurred.  So if you click on a log entry because you need to highlight it while troubleshooting firewall issues, the entry will be de-selected by the time you return from looking at another window.

**Comment by wokhan** [comment]
We'll check this asap. Thank for your feedback and sorry for the delay!

**Comment by harrwiss** [comment]
This behaviour was fixed in feature u1-eventlog i.e. when you click on a row, "Auto refresh" for the security log is stopped automatically.

**Comment by wokhan** [comment]
Closed since resolved by @harrwiss.
