### ISSUE TITLE
Native Windows notifications

### ISSUE THREAD

**Issue by vlldk** [wokhansoft/WFN#40]
Like [this](https://media.springernature.com/lw785/springer-static/image/chp%3A10.1007%2F978-1-4842-0719-2_14/MediaObjects/978-1-4842-0719-2_14_Fig4_HTML.jpg)

Not sure how "advanced rule setting" would be implemented tho...

**Comment by wokhan** [comment]
Indeed, we would have to customize that anyway (or allow a two steps access: first the notification balloon, including a link to access advanced settings...). Maybe a theme engine would be more appropriate if you want some customization?

**Comment by wokhan** [comment]
We might switch to the Windows 10 notification engine once every user (and potential one...) has moved to Win10, in the meantime we'll have to keep using a custom window so that it works on Win7 (or Win8... does anyone still use that?) as well.
Closing the issue.
