### ISSUE TITLE
Alert Notification Popup Should Resolve IP Address To Hostname (DNS Record)

### ISSUE THREAD

**Issue by BADJAG** [wokhansoft/WFN#43]
Hi, I'd like to propose a minor enhancement to the alert notification popup. In the "ADVANCED RULE SETTINGS" section of the popup, it'd be nice if the "TARGET" IP address resolved to a hostname as well. This would save the effort of having to look up the destination IP via traceroute or a reverse IP lookup on the web. Thanks.

**Comment by AtlasHackert** [comment]
The biggest problem with that is that reverse DNS isn't trustworthy; it's easy to forge the record, or have it display the wrong one (there can be multiple domains associated with one IP). Showing information that can be wrong is a bad idea for security software.

That said: if somebody figures out a compromise, it's definitely something valuable to have.

**Comment by wokhan** [comment]
Hi,

This feature was implemented a while back but wasn't working everytime. It should still be there anyway… I don't remember disabling it :-)

Thanks

Khan

________________________________
De : BADJAG <notifications@github.com>
Envoyé : Monday, July 23, 2018 12:23:28 AM
À : wokhansoft/WFN
Cc : Subscribed
Objet : Re: [wokhansoft/WFN] Alert Notification Popup Should Resolve IP Address To Hostname (DNS Record) (#43)


Thanks for the quick reply. I guess using traceroute will have to do for the time being. It's more fun anyway. :-)

**Comment by AtlasHackert** [comment]
I disabled it some time ago for two reasons: the one stated above, and the DNS lookup was itself triggering WFN notifications.

**Comment by wokhan** [comment]
Ok, makes sense :-) Sorry I missed this.
Thank you


________________________________
De : DanielPharos <notifications@github.com>
Envoyé : Tuesday, July 24, 2018 12:42:41 AM
À : wokhansoft/WFN
Cc : Jérôme Saliba; Comment
Objet : Re: [wokhansoft/WFN] Alert Notification Popup Should Resolve IP Address To Hostname (DNS Record) (#43)


I disabled it some time ago for two reasons: the one stated above, and the DNS lookup was itself triggering WFN notifications.

**Comment by harrwiss** [comment]
This is in the pipeline - implemented a DNS resolver working in the background. Currently working on integration with SecurityLog and then maybe Map and Connections

**Comment by harrwiss** [comment]
DNS Resolver is implemented for Security Log, Connections, Map and Notifier (tooltip on Target IP option). However today there are many host IP's which have no DNS entry resulting in *No such host is known* when resolved. If you click on the *Target IP* link in Notifier it will do a lookup on an online service to get more details.

Note: Just noticed, that clicking on the *Target IP* link in Notifier crashes in the netcore3 version.

**Comment by wokhan** [comment]
Any crashing with netcore31 should be due to missing assemblies (since they are now pulled from nuget). Hopefully 😁

**Comment by harrwiss** [comment]
Crash fixed with #76

**Comment by harrwiss** [comment]
Btw: The TargetInfoUrl and TargetPortUrl for the online service to use can be configured in the settings config file.
