### ISSUE TITLE
[Alert dialog | Advanced Rule Settings] implement LAN toggle for target destination

### ISSUE THREAD

**Issue by kekukui** [wokhansoft/WFN#46]
**While using a VPN I have seen alerts in 'PrivateFirewall' for outgoing netBIOS traffic on port 137 to public IP addresses.  At the same time, I have seen WFN alert on traffic to local addresses as shown in the picture below.  But the alert dialog only allows you to create rules which target port, protocol or single IP address -- it appears that you cannot create rules for a zone (such as LAN or WAN).  Since the home network is trusted, I want to allow outbound SMB/netBIOS traffic to anything on the LAN -- I do not want to explicitly authorize every IP in the LAN.  Will enabling the "Profile: Private" toggle accomplish this?**

![wfn lan traffic](https://user-images.githubusercontent.com/20834957/43257001-7db12d96-909c-11e8-8d45-2bc489c1374d.PNG)

**Comment by wokhan** [comment]
Sorry for the delay. If you only set the private profile on actually private networks (ie LAN), it should be indeed easier for you to untick everything but the profile to create global rules. But I guess you moved on months ago :-/

**Comment by kekukui** [comment]
I still follow this project, but am using a different firewall now and waiting for beta 4 😉
