### ISSUE TITLE
Feature Request: Automatic "Block Silently" with temporary "Block & Prompt"

### ISSUE THREAD

**Issue by a-raccoon** [wokhansoft/WFN#48]
This feature request is in extension to my earlier Issue about Notifier.exe Death Battles (I don't know how to link to it, but here's the url:  https://github.com/wokhansoft/WFN/issues/28 )

When WFN 'Firewall Settings' is in "Block & Prompt" mode, the Windows Task Scheduler will launch Notifier.exe for each connection attempt, to determine whether a user prompt is necessary.  When the setting is in "Block Silently" mode, then WFN's Notifier is not launched and no CPU resources are utilized.

I find that 99% of the time, I am quite contented to leave WFN in this latter mode, to silently block all connection attempts that are not already approved.  It's only when I install a new piece of software that I will proactively switch WFN to "Block & Prompt" briefly so that I can receive notification of the requested connection(s).  Once I have sorted out which connections are needed to make the software work, I switch WFN back to "Block Silently" for the next long while.

The problem here is that I have to manually tick six radio buttons from "Block Silently" to "Block & Prompt", then tick the six radio buttons to set it back to "Block Silently" again.  I would like to request two things:

1:  Make these six clicks simplified to a 1 click minimalist solution.  I believe most people maintain only a single set of firewall rules, applicable across whichever profile(s) they incidentally use.  So, apply rules to all 3 profiles in unity by default, for least amount of confusion.  And also monitor requests for both Inbound and Outbound connections in tandem, with the same one click.

2:  Make this a temporary / momentary feature that is quickly accessible from a right-click systray icon menu, rather than GUI navigation.  Enabling "Block & Prompt" for only as long as necessary until it times out and switches back to "Block Silently."

**Comment by wokhan** [comment]
Sorry for the looong delay, this is a good idea. We will add this (as usual, no ETA...).

**Comment by harrwiss** [comment]
> 1... apply rules to all 3 profiles in unity by default

This was implemented a while ago (All section) but is not yet in the current build (Beta 3) yet.
![2019-10-20 13_35_40-](https://user-images.githubusercontent.com/33778373/67158984-363d7f80-f33f-11e9-942a-5052ae229d95.png)

> 2: Make this a temporary / momentary feature that is quickly accessible from a right-click systray icon menu, rather than GUI navigation

Clicking on the orange shield image opens WFN directly, but this only helps when the notifier is visible. I agree a systray icon would be nicer.
![2019-10-20 13_41_51-WFN - Notification](https://user-images.githubusercontent.com/33778373/67159027-9fbd8e00-f33f-11e9-8e24-850745a7d552.png)

**Comment by harrwiss** [comment]
Notifier can now be started, closed or minimized on demand - no need anymore to switch back an forth. Systray and right-click menu has also been implemented. Think we can close the issue.
