### ISSUE TITLE
Allow temporarily is invalid now

### ISSUE THREAD

**Issue by African-Networks** [wokhansoft/WFN#5]
Notification window is stuck until clicked icon on taskbar, to remove temporary rule, and yet permanent allow rule is created. W7, beta 2.

Blocking seems to work fine now, thanks.
Can you add "EnableWFN.cmd" to setup without GUI?

**Comment by AtlasHackert** [comment]
> Notification window is stuck...

Indeed sounds like a bug; I'll check it out.

> Can you add "EnableWFN.cmd" to setup without GUI?

Not sure how easy that is, but I'll see what I can do. Although honestly, I'd rather get rid of the Disable-batch-file...

**Comment by bsassone** [comment]
I'm seeing the same thing.

**Comment by AtlasHackert** [comment]
This issue has been fixed in the just released v2.0 Beta 3!
