### ISSUE TITLE
WFNV20BETA3 is automatically creating rules.

### ISSUE THREAD

**Issue by mariohenriquelopes3** [wokhansoft/WFN#52]
When I set up "Block and prompt", WFNV20BETA3 is automatically creating outgoing rules.
1 Custom Rule - Serviço de transferência inteligente de tela de fundo(auto) [R:80,443]
2 Custom Rule - Serviços de criptografia(auto) [R:80]
3 Custom Rule - Windows Applications (auto)
4 Custom Rule - Windows Update (auto) [R:80,443]

**Comment by wokhan** [comment]
Indeed, if we don't do that, Windows won't be happy and WFN will not prompt you to create these rules as they are required by hosted services (ie. in another process) and hardly detectable.

**Comment by mariohenriquelopes3** [comment]
I understand now, Thanks!
