### ISSUE TITLE
change github description

### ISSUE THREAD

**Issue by alkorsan** [wokhansoft/WFN#58]
Hi,
using the global search of github do not show you in the results for a simple keywords like : windows firewall. 
this is because github search only in the description of the repository not the readme when searching for  repositories.

please change the description to something meaninfull for the search engine.

the actual one is:

> This repository hosts source code for the WFN tool (previously on codeplex). You can also find binary releases at https://github.com/wokhansoft/WFN/releases.

I suggest:

> Windows Firewall Notifier extends the default Windows embedded firewall by allowing to handle and notify about outgoing connections, offers real time connections monitoring, connections map, bandwidth usage monitoring and more...

thank you for this beautifull work.

**Comment by wokhan** [comment]
Thank you! I'll update it right now... And as I'm a bit lazy I'll directly use your suggestion :wink:
