### ISSUE TITLE
Disable UAC for Rule Manager

### ISSUE THREAD

**Issue by sumdog** [wokhansoft/WFN#60]
When using WFN, each time I allow or block a given network request, I get a UAC prompt in Windows 10 for RuleManager. I [disabled UAC for RuleManager using the Microsoft Application Comparability Tools](https://mynuuo.zendesk.com/hc/en-us/articles/360000764413-How-to-disable-UAC-for-a-specific-program). 

Now if I double click on it, I get the "RuleManager cannot be run manually" without a UAC prompt, but when WFN calls it for adding new rules, I still get the prompt. I've tried adding WFN to the same Comparability Tools Database with `RunAsInvoker` and `RunAsAdmin` as well and I still get the prompt.

Is there any way to disable this prompt, or sign it with a cert we can create locally and import?

**Comment by harrwiss** [comment]
Same problem with the UAC prompt always coming up when I allow or block a request - any workaround for this?

**Comment by AtlasHackert** [comment]
WFN needs administrator rights in order to make/modify firewall rules. So the only "workaround" is to use an administrator account. Which is a huge security risk, so please don't.

**Comment by harrwiss** [comment]
Since I changed my way to use "Block silently" mode normally and only turning on "Block and prompt" when I need to add a new rule for a specific process, the UAC prompt is not bothering me so much anymore.

**Comment by wokhan** [comment]
Closing this issue. It would require a "try first without elevation" and "retry with elevation if the former failed" which is not worth implementing. 
Thanks you all
