### ISSUE TITLE
New features and license

### ISSUE THREAD

**Issue by harrwiss** [wokhansoft/WFN#66]
Hi, I would like to ask 2 things:
1) Are you still accepting/interested in pull requests? If yes I'll create one :)
2) Would you by chance consider changing the license from GPL to Apache 2.0?
Thx.

**Comment by wokhan** [comment]
Hi, yes of course you can create PRs, anything that could make this project evolve is welcome 😉
I'll have a look at the licence, could you please tell what motivates your request?

**Comment by harrwiss** [comment]
Great, I just created the PR containing all the stuff I did during the last few weeks - have fun :wink:

Regarding the license question GPL is quite limiting for many investing considerable time into enhancing the project and as a consequence can hinder collaboration from my point of view.  However most of my experience is in the java ecosystem where we rather not touch GPL licensed code. 
For me this is currently only a hobby project to learn something new and because it's useful :thumbsup:

**Comment by harrwiss** [comment]
@AtlasHackert Thx for merging my prev PR btw. Next one is on the way.
