### ISSUE TITLE
Use async operations and tasks to lower UI thread blocking

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#80]
Adding (back) async for resource consuming operations (DNS resolution and icon retrieval). Should improve performance again.

**Comment by wokhan** [comment]
This issue is (partly) implemented as part of the bugfix/securitylog_perf branch update (yeah, I know...).
@harrwiss, I refactored the DnsResolver (a lot, but it's still the same logic as yours) since the list resolution is an anti pattern (no offense ;-) ). One should only compute information if and when it's needed (relying on the lazy binding in virtualized grids).

**Comment by wokhan** [comment]
Oh and I removed (again) the limitation on the security log.
There is one known bug: an index out of range exception which is a bit awkward (occurs in .Net internal classes due to the list being updated while being traversed). I'll check that later.
Performance _should_ be OK (and memory / CPU usage as well... i.e. better than before), but I haven't enough time to test thoroughly.

**Comment by harrwiss** [comment]
Hi @wokhan 

> One should only compute information if and when it's needed (relying on the lazy binding in virtualized grids).

No offense taken - if that can be improved as you describe than that's perfect 👍 I'll check it out.

> Performance should be OK (and memory / CPU usage as well... i.e. better than before), but I haven't enough time to test thoroughly.

Will do some tests and let you know if there is anything obvious coming up.

**Comment by harrwiss** [comment]
Hi @wokhan, 
the security log performs overall much better then before - I like it 👍 

Didn't experience the error you mentioned above but noticed some missbehaviour here:

![image](https://user-images.githubusercontent.com/33778373/76447789-8c33c200-63c9-11ea-807a-969bb88a6b6b.png)

a) when initially opening it, the items count stays a bit below the max on the right but never reaches max when fully loaded (don't know why).

b) then, when playing around a bit, there comes a situation (can't reliably reproduce it) that the items count goes above the max on the right and then continues to grow continuously (as you see in the picture).

In the debug output I see now every second or so:
```
*System.Net.Sockets.SocketException' in System.Net.NameResolution.dll*
and sometimes in between *Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll*
```
Maybe you know where the problem could be?

Cheers.

btw: Now that it's so fast, we should probably introduce a name filter possibility similar to rules.

**Comment by wokhan** [comment]
I wonder if the max is actually a max... Meaning that EventLog.Count might be plain wrong... I cannot see any other reason, mainly because I guess you didn't have 90k new connections after you opened the page 🤔
Regarding exceptions, they should have been there already (even if catched), weren't they?

**Comment by widi8835** [comment]
> Oh and I removed (again) the limitation on the security log.
> There is one known bug: an index out of range exception which is a bit awkward (occurs in .Net internal classes due to the list being updated while being traversed). I'll check that later.
> Performance _should_ be OK (and memory / CPU usage as well... i.e. better than before), but I haven't enough time to test thoroughly.

Hi there,
do you have some information about the 'index out of range exception'? It sounds that this is very similar to some exceptions in WPF that I had fun with a few month ago. Maybe I can help (hopeful I can find some free time at the weekend).

**Comment by harrwiss** [comment]
Hi @wokhan 
> they should have been there already (even if catched), weren't they?

That could be (think the DNS resolution causes them when it can't  resolve deeper down), my concern was more that they appeared constantly when the described scenario happened.

**Comment by wokhan** [comment]
Hi @widi8835, nice to see "old" WFNers back ;-)
The index out of range comes from an internal cache data retrieval when scanning for entries in an event log.
I think it's because we are now enumerating events while also monitoring newly added ones, it somehow breaks the internal cache, but I would have been less surprised if data was "just" mixed up instead of throwing an exception... except if we are above the max limit of the event log, say it cached an entry that has been removed, and internally still tries to access it.
It can occur if MS implementation relies on the event ID and not its actual index in the events array => I'll check their code.

Hi @harrwiss, I'll quickly check, I added a log to ensure it's not simply because malformed IPs that when through. Will tell in a few minutes.

**Comment by wokhan** [comment]
I pushed a minor update (see the last commit). Could improve performance a bit since I forgot to filter out non-matching log entries for real time additions.
I won't be able to do anything more today, maybe tomorrow morning :)
Have a nice day, all!
