### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#85]
1. Refactor projects to get rid of the "Helpers" pattern (see Common.Net.Dns). 

2. All classes should be in separate files, also.

3. Follow Roslyn guidance (not every time but.. .) with :
- contracts for null checking
- accessors (use short form when readable) 
- method and variable names
- public fields that should be property
- ...... 

4. Use "is null" instead of == null

That should be enough for now 🤔😁

**Comment by wokhan** [comment]
Working on this right now, @harrwiss & @AtlasHackert, a lot of namespaces will change but I attempt to keep everything as-is (implementation-wise), except when I see easy improvements on the way. Deeper refactoring might come later (i.e. method signature modifications or alike).

**Comment by harrwiss** [comment]
Hi @wokhan, I had a look at *contracts for null checking* during compile time (static analysis) but it turned out that the referenced project to be dead/stuck [see link](https://github.com/microsoft/CodeContracts/issues/409). If you have any good suggestions, let me know.

Also, I started this morning on #94 in the Console/InstallHelper pending the "mimimize" change in Notifier.

**Comment by wokhan** [comment]
Hi @harrwiss, I have to say I'm a bit disappointed... In fact I "discovered" Contracts following Roslyn FxCop's analyzers recommendations, and now that I read the link you provided (and some others), I understand as well that in fact Contracts are not really maintained (while they still work...). MS should double check their own recommendations, I guess... And too bad as I really think it was a great idea.
Anyway, I'll drive-test the non-nullable reference type C# 8 offers instead (which would remove the use of such checks for null values in the first place). Nullable would then have to be explicitly defined as such (using the _class_? notation), while all reference types would be non-nullable by default (preventing the need for null checks).
If it goes as expected, Contracts wouldn't be that mandatory...

**Comment by wokhan** [comment]
Hi @harrwiss & @AtlasHackert  (hope you're fine Daniel, haven't seen you in a while!!!)
As you said @harrwiss I should push modifications frequently, but I don't like pushing WIP and I'm in the middle of a huge refactoring (sorry about that, another bad habit).
I'm sorry to ask, but do you think it would be ok to put your modifications on hold for say... 3 days? (apart from the last PR I'll approve once our discussions are resolved of course).
I have about 600 warnings to fix (due to the activation of the Nullable support of c# 8 in the Common project, which I think is a clever thing....)
To keep it short: only reference types set as nullable with "?" can actually be null (as in "we know they can so it's handled properly"). Standard ref types are considered as not nullable (so passing null can fail with a null ref exception - but this is now up to the devs to check if the type is a nullable, it's way better this way since we _know_ when things might go wrong or not).
Btw I cannot go back now that I started migrating all types ;)
Thanks

**Comment by harrwiss** [comment]
Hi @wokhan, ok then I look forward to an all clean code-base without warnings 😁 - can imagine it'll take some effort to finish. Cheers.

**Comment by wokhan** [comment]
Hi @harrwiss I hope it won't take that much of an effort since I'm back at work (sort of, working from home), and it will let me only 1h a day... :-P
Will tell you once done.
