### ISSUE TITLE
UI needs an update

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#86]
- Consider moving to MahApps (already used in one of my apps, looks great and modern though a bit "big").
- If not, will improve all layouts and designs for something more "modern" as well.

Note: I keep that one selfishly for myself ;-)

**Comment by Runnin-N-Gunnin** [comment]
Hello wokhan. Great software. I'm new to github so feel free to remove if I comment in the wrong place.

In Issue #73 you said:

"I'm confident it can regain users (as in power users) attention. I don't want it to be a software for non power-users as I have no time to support them... "

Question: If you want to avoid non power-users how will changing the UI help? A real power-user would rarely care about the UI - they care about functionality, customization and output - like WinForm controls (or WPF) or verbose outputs from a console.

MahApps will scare power-users away. My opinion only.

Thanks.

**Comment by wokhan** [comment]
Hi! thanks for your comment :-)

Well, I wasn't about to use MahApps as-is, but with some tweaks only to have a "moderner" look and feel. MahApps is still 100% WPF so highly customizable...
I might also not use it at all as mentioned in second bullet.

BTW it's not high priority. I've some minor design changes in mind, which won't modify the app that much (same layout, different buttons / menu rendering, for instance).

I'm also a power user, but I like "beautiful" UI as well ;-)

**Comment by wokhan** [comment]
Hi,
As said in the other issue, I'm partly rewriting the ActivityWindow / Notifier UI (and updating the console's one, while keeping things as they are - refactoring to use controls instead of rewriting styles everywhere... which I shouldn't have in the first place, but... well... it was years ago ;-) ).
@harrwiss, I saw that you sometime updated the view through the code: it's best to use Bindings for this (even if they are based on Reflection in WPF and hence are not really the best in terms of performance). Checkboxes can then be used to toggle other controls visibility using Visibility={Binding IsChecked,ElementName=myCheckBox} (except that it looks like we need a converter with .Net Core 3.1 WPF flavor, while it wasn't needed anymore with full framework). I included one (very simple) through my Wokhan.UI library, and updated the XAML code accordingly.
I've to stop for today, but I'll post some screenshots soon!

**Comment by wokhan** [comment]
Almost done, still need a few tweaks but actual free time was sparse those last months.

The changes include: 
- new design for the activity window (while).
![Annotation 2020-06-23 081711](https://user-images.githubusercontent.com/24826061/85367800-47700900-b52a-11ea-8d60-7b0c9462cc23.png)

- simplified controls (using Wokhan.UI XAML extensions - a yet unpublished version - to add images and headers, for instance, while keeping standard controls and reducing amount of required code). As said it won't change how they actually look, and will make any future update / switch to any lib easier.
- new window layout leveraging the CustomChrome feature of .Net 4.6 / .Net Core (through Wokhan.UI also).
![Annotation 2020-06-23 0817112](https://user-images.githubusercontent.com/24826061/85367808-49d26300-b52a-11ea-8a93-9e996d6da766.png)
![Annotation 2020-06-23 08171123](https://user-images.githubusercontent.com/24826061/85367815-4c34bd00-b52a-11ea-9bca-5a8339f0a11d.png)
![Annotation 2020-06-23 082255](https://user-images.githubusercontent.com/24826061/85368055-cd8c4f80-b52a-11ea-8ab8-dacc314413dc.png)

Notifier design also changed a bit, I'll also post screenshots later.

Please note it's still a work in progress but the overall design shouldn't change much anymore.
I hope you'll like it.

Btw, would anyone be interested by a dark mode?

Thanks

**Comment by wokhan** [comment]
Branch features/ui_controls has been pushed.
Known issue: the tooltips won't work anymore (working on it), including the "help" button tooltip.

Merging will be requested once fixed, so this is a WIP.

**Comment by Technetium1** [comment]
This seems like it might be the appropriate place to mention that in the Map section, resolved DNS is not re-sizable as of release `wfn-x64-full-nightly-no-test-20200518-6ffc2e`. Scrolling sideways looks and feels weird.

**Comment by wokhan** [comment]
Hi @Technetium1, thanks for your feedback: indeed it was the right place and I changed the behavior to:
1. Allow resizing the connections list so that the DNS name column gets resized accordingly
2. Add the resolved DNS name as a tooltip so that it can be quickly checked
Both fixes are part of the UI update and aren't merged with the nightly / main branch (should do that soon...).
