### ISSUE TITLE
Fix [unkown] eventId:5158 occuring on port 6 / protocol 36 (incoming connection)

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#87]
Error: Cannot get filter rule - value cannot be null (when clicking on the action link)

**Comment by harrwiss** [comment]
Did you fix this maybe?

With this:

![image](https://user-images.githubusercontent.com/33778373/76687373-8cc79500-6623-11ea-9f4c-62197d634c07.png)

[FIX] Added protocol 36 (found in some exceptions)
[FIX] [Sec log] Added a check for events added in real time (was missing)
[IMP] Added (or added back) a log to track DNS resolution failure reasons

**Comment by wokhan** [comment]
Hi @harrwiss, it might indeed be fixed, but since I didn't reproduce it in the first place, I cannot tell for sure...
