### ISSUE TITLE
Will not start / .NET Core not detected [2.1 nightly]

### ISSUE THREAD

**Issue by kekukui** [wokhansoft/WFN#95]
![image](https://user-images.githubusercontent.com/20834957/76822720-4a9b8080-67e8-11ea-8458-653158846252.png)

![image](https://user-images.githubusercontent.com/20834957/76822966-fe9d0b80-67e8-11ea-8477-f432a3b7cc81.png)

**Comment by wokhan** [comment]
Hi @kekukui, thank you for your feedback. That's a weird issue, indeed...
Anyway nightlies have been disabled (temporarily), I was playing around with them but wasn't able to test the output yesterday (sorry about that).
Will come back soon!

**Comment by wokhan** [comment]
Nightly has been republished, using .Net Core 3.1.2 this time (maybe it was the reason why it wasn't working for you?).
Feel free to tell if not!
Thanks

**Comment by kekukui** [comment]
The issue persists... but I found something else in Event Viewer - Event ID 1023:

```
Description: A .NET Core application failed.
Application: WFN.exe
Path: C:\Windows Firewall Notifier\WFN.exe
```
Message: A fatal error occurred. The required library `hostfxr.dll` could not be found.
If this is a self-contained application, that library should exist in [C:\Windows Firewall Notifier\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win7-x64

**Comment by hoasis2** [comment]
> 
>     * https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win7-x64

Uninstall ASP.NET Core Runtime 3.1.2 first and install [Desktop Runtime 3.1.2 x64](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.2-windows-x64-installer) instead.

**Comment by wokhan** [comment]
Thank you for investigating!
We can also publish a self-contained version if you're interested. At least it would confirm it works and doesn't come from some other system-related weirdness!

**Comment by wokhan** [comment]
Standalone versions are available for x64 and x86 systems (still as nightlies of course).
Feel free to give it another try ;-)
Thanks
