### ISSUE TITLE
Will not start / Windows Firewall Error

### ISSUE THREAD

**Issue by RafaelDominiquini** [wokhansoft/WFN#96]
I'm unable to run the last version of the app (2.1 Nightly):

![WFN_TjqAPGfA9v](https://user-images.githubusercontent.com/61922887/76823345-b4208c80-67f2-11ea-8e50-47fe90f9b367.png)

The version 2.0 Beta 3 is ok!

Thanks.

**Comment by wokhan** [comment]
Hi,
Thank you for your feedback!
Nightlies publication for WFN is a work-in-progress and wasn't fully tested yet.
I disabled it until I'm sure it works as expected.
Sorry for the issue you faced, of course we'll ensure it's *at least* launching before publishing ;-)

**Comment by wokhan** [comment]
Note: it's only due to the config file not being copied when publishing.
Might be fixed very very soon.

**Comment by wokhan** [comment]
Fixed ;-)
Please feel free to try the last build @RafaelDominiquini ! (it contains unfinished features, so please keep that in mind!).
Thanks
