### ISSUE TITLE
".github" directory should probably be excluded from the repository

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#98]
Created by @harrwiss through the project page

With the "workflows\dotnetcore.yml" in the *.github" directory I experienced authentication problems when trying to push to my fork master. 

Strangely I had to remove my github credentials using Credential Manager to be able again to push again (got this hint after some googling). After that, the workflow was also active on my fork :(

If possible the contents of the .github folder should therefore be excluded I think.

**Comment by wokhan** [comment]
Hi (again) @harrwiss,
GitHub itself creates the file in this folder, I guess workflows cannot be anywhere else....
Excluding it would then disable workflows / github actions, which is not something we'd like :-/
I don't understand why it broke your github as I've had no issues at all.
I keep this as an issue to figure out what happened anyway.
Thanks

**Comment by harrwiss** [comment]
Hi @wokhan, 
it was a security issue that did you not allow to push a workflow wihtout refreshing the token, but it took me a while to figure it out - could be that others will have the same problem 🤔 . The other thing is, that after the push it started to execute the workflow 💣 which is kind of strange when you suddenly get build failures by mail.

Don't know what could be done to avoid this though.

**Comment by wokhan** [comment]
Hi @harrwiss, regarding the security issue, it's indeed weird as I didn't have to do anything like that (maybe because I'm owner?).
And I guess the workflow was triggered because I only kept on:push without specifying a branch in a former commit :-/ Sorry about that. I had to do it by trial and error since I cannot test workflows locally (but I should probably have done this on a separated branch anyway...)
Cheers

**Comment by harrwiss** [comment]
Hi @wokhan , don't worry, you coudn't have known this happens in another fork - maybe it was only me 😄 I wanted to test the workflow with nunit in my fork, but instead was troubleshooting push problems 💣

**Comment by wokhan** [comment]
Closing this now as there won't be any follow ups (I guess ;-) ).
